#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include "cnrt.h"

// Global Variables

// Forward Declarations
int main();

int main() {
  cn_rt_init();
  long long r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22;

  entry:
  cn_rt_print_string("========== 二进制字面量 ==========\n");
  int cn_var_标志位;
  cn_var_标志位 = 240;
  int cn_var_掩码1;
  cn_var_掩码1 = 170;
  int cn_var_掩码2;
  cn_var_掩码2 = 85;
  int cn_var_位0;
  cn_var_位0 = 1;
  int cn_var_位1;
  cn_var_位1 = 2;
  int cn_var_位2;
  cn_var_位2 = 4;
  int cn_var_位3;
  cn_var_位3 = 8;
  int cn_var_位7;
  cn_var_位7 = 128;
  int cn_var_零字节;
  cn_var_零字节 = 0;
  int cn_var_满字节;
  cn_var_满字节 = 255;
  cn_rt_print_string("标志位 (0b11110000): ");
  r0 = cn_var_标志位;
  cn_rt_print_int(r0);
  cn_rt_print_string("\n");
  cn_rt_print_string("掩码1 (0b10101010): ");
  r1 = cn_var_掩码1;
  cn_rt_print_int(r1);
  cn_rt_print_string("\n");
  cn_rt_print_string("掩码2 (0B01010101): ");
  r2 = cn_var_掩码2;
  cn_rt_print_int(r2);
  cn_rt_print_string("\n");
  cn_rt_print_string("位7 (0b10000000): ");
  r3 = cn_var_位7;
  cn_rt_print_int(r3);
  cn_rt_print_string("\n");
  int cn_var_与运算;
  r4 = 10;
  cn_var_与运算 = r4;
  int cn_var_或运算;
  r5 = 15;
  cn_var_或运算 = r5;
  int cn_var_异或运算;
  r6 = 6;
  cn_var_异或运算 = r6;
  cn_rt_print_string("0b1111 & 0b1010 = ");
  r7 = cn_var_与运算;
  cn_rt_print_int(r7);
  cn_rt_print_string("\n");
  cn_rt_print_string("0b1010 | 0b0101 = ");
  r8 = cn_var_或运算;
  cn_rt_print_int(r8);
  cn_rt_print_string("\n");
  cn_rt_print_string("0b1100 ^ 0b1010 = ");
  r9 = cn_var_异或运算;
  cn_rt_print_int(r9);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 八进制字面量 ==========\n");
  int cn_var_权限755;
  cn_var_权限755 = 493;
  int cn_var_权限644;
  cn_var_权限644 = 420;
  int cn_var_权限600;
  cn_var_权限600 = 384;
  int cn_var_权限777;
  cn_var_权限777 = 511;
  int cn_var_权限000;
  cn_var_权限000 = 0;
  int cn_var_八进制1;
  cn_var_八进制1 = 83;
  int cn_var_八进制2;
  cn_var_八进制2 = 302;
  int cn_var_零八进制;
  cn_var_零八进制 = 0;
  int cn_var_七;
  cn_var_七 = 7;
  int cn_var_八;
  cn_var_八 = 8;
  int cn_var_六十四;
  cn_var_六十四 = 64;
  cn_rt_print_string("权限755 (0o755): ");
  r10 = cn_var_权限755;
  cn_rt_print_int(r10);
  cn_rt_print_string("\n");
  cn_rt_print_string("权限644 (0o644): ");
  r11 = cn_var_权限644;
  cn_rt_print_int(r11);
  cn_rt_print_string("\n");
  cn_rt_print_string("权限777 (0o777): ");
  r12 = cn_var_权限777;
  cn_rt_print_int(r12);
  cn_rt_print_string("\n");
  cn_rt_print_string("八进制123 (0o123): ");
  r13 = cn_var_八进制1;
  cn_rt_print_int(r13);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 混合进制运算 ==========\n");
  int cn_var_混合和1;
  r14 = 30;
  cn_var_混合和1 = r14;
  int cn_var_混合和2;
  r15 = 24;
  cn_var_混合和2 = r15;
  int cn_var_混合和3;
  r16 = 20;
  cn_var_混合和3 = r16;
  cn_rt_print_string("0b1111 + 0o17 = ");
  r17 = cn_var_混合和1;
  cn_rt_print_int(r17);
  cn_rt_print_string("\n");
  cn_rt_print_string("0x10 + 0o10 = ");
  r18 = cn_var_混合和2;
  cn_rt_print_int(r18);
  cn_rt_print_string("\n");
  cn_rt_print_string("0b1010 + 0x0A = ");
  r19 = cn_var_混合和3;
  cn_rt_print_int(r19);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 实际应用场景 ==========\n");
  int cn_var_子网掩码24位;
  cn_var_子网掩码24位 = -256;
  int cn_var_可执行文件权限;
  cn_var_可执行文件权限 = 493;
  int cn_var_配置文件权限;
  cn_var_配置文件权限 = 420;
  int cn_var_红色通道;
  cn_var_红色通道 = 255;
  int cn_var_绿色通道掩码;
  cn_var_绿色通道掩码 = 8355840;
  cn_rt_print_string("24位子网掩码: ");
  r20 = cn_var_子网掩码24位;
  cn_rt_print_int(r20);
  cn_rt_print_string("\n");
  cn_rt_print_string("可执行文件权限: ");
  r21 = cn_var_可执行文件权限;
  cn_rt_print_int(r21);
  cn_rt_print_string("\n");
  cn_rt_print_string("配置文件权限: ");
  r22 = cn_var_配置文件权限;
  cn_rt_print_int(r22);
  cn_rt_print_string("\n");
  return 0;
  cn_rt_exit();
}

