#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include "cnrt.h"

// Global Variables

// Forward Declarations
int main();

int main() {
  cn_rt_init();
  double r0;
  double r1;
  double r2;
  double r3;
  double r4;
  double r5;
  double r6;
  double r7;
  double r8;
  double r9;
  double r10;
  double r11;
  double r12;
  double r13;
  double r14;
  double r15;
  double r16;
  double r17;
  double r18;
  double r19;
  double r20;
  double r21;
  double r22;
  double r23;

  entry:
  cn_rt_print_string("========== 基础科学计数法 ==========\n");
  double cn_var_avogadro;
  cn_var_avogadro = 602214075999999987023872.000000;
  double cn_var_light_speed;
  cn_var_light_speed = 299792458.000000;
  double cn_var_planck;
  cn_var_planck = 0.000000;
  cn_rt_print_string("阿伏伽德罗常数: ");
  r0 = cn_var_avogadro;
  cn_rt_print_float(r0);
  cn_rt_print_string("\n");
  cn_rt_print_string("光速 (m/s): ");
  r1 = cn_var_light_speed;
  cn_rt_print_float(r1);
  cn_rt_print_string("\n");
  cn_rt_print_string("普朗克常数: ");
  r2 = cn_var_planck;
  cn_rt_print_float(r2);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 不同指数形式 ==========\n");
  double cn_var_billion;
  cn_var_billion = 1000000000.000000;
  double cn_var_trillion;
  cn_var_trillion = 1000000000000.000000;
  double cn_var_large_num;
  cn_var_large_num = 15000000000.000000;
  cn_rt_print_string("十亿: ");
  r3 = cn_var_billion;
  cn_rt_print_float(r3);
  cn_rt_print_string("\n");
  cn_rt_print_string("万亿: ");
  r4 = cn_var_trillion;
  cn_rt_print_float(r4);
  cn_rt_print_string("\n");
  cn_rt_print_string("1.5e10: ");
  r5 = cn_var_large_num;
  cn_rt_print_float(r5);
  cn_rt_print_string("\n");
  double cn_var_micro;
  cn_var_micro = 0.000001;
  double cn_var_nano;
  cn_var_nano = 0.000000;
  double cn_var_small_num;
  cn_var_small_num = 0.000023;
  cn_rt_print_string("微 (1e-6): ");
  r6 = cn_var_micro;
  cn_rt_print_float(r6);
  cn_rt_print_string("\n");
  cn_rt_print_string("纳 (1e-9): ");
  r7 = cn_var_nano;
  cn_rt_print_float(r7);
  cn_rt_print_string("\n");
  cn_rt_print_string("2.3E-5: ");
  r8 = cn_var_small_num;
  cn_rt_print_float(r8);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 大小写混合 ==========\n");
  double cn_var_lower_e;
  cn_var_lower_e = 314.000000;
  double cn_var_upper_e;
  cn_var_upper_e = 271.800000;
  cn_rt_print_string("3.14e2 (小写e): ");
  r9 = cn_var_lower_e;
  cn_rt_print_float(r9);
  cn_rt_print_string("\n");
  cn_rt_print_string("2.718E2 (大写E): ");
  r10 = cn_var_upper_e;
  cn_rt_print_float(r10);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 显式正号 ==========\n");
  double cn_var_explicit_plus;
  cn_var_explicit_plus = 100000.000000;
  double cn_var_explicit_minus;
  cn_var_explicit_minus = 0.000010;
  cn_rt_print_string("1.0e+5: ");
  r11 = cn_var_explicit_plus;
  cn_rt_print_float(r11);
  cn_rt_print_string("\n");
  cn_rt_print_string("1.0e-5: ");
  r12 = cn_var_explicit_minus;
  cn_rt_print_float(r12);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 整数科学计数法 ==========\n");
  double cn_var_int_scientific1;
  cn_var_int_scientific1 = 5000.000000;
  double cn_var_int_scientific2;
  cn_var_int_scientific2 = 0.000200;
  cn_rt_print_string("5e3: ");
  r13 = cn_var_int_scientific1;
  cn_rt_print_float(r13);
  cn_rt_print_string("\n");
  cn_rt_print_string("2e-4: ");
  r14 = cn_var_int_scientific2;
  cn_rt_print_float(r14);
  cn_rt_print_string("\n");
  cn_rt_print_string("\n========== 实际应用场景 ==========\n");
  double cn_var_electron_mass;
  cn_var_electron_mass = 0.000000;
  double cn_var_proton_mass;
  cn_var_proton_mass = 0.000000;
  double cn_var_gravitational_const;
  cn_var_gravitational_const = 0.000000;
  cn_rt_print_string("电子质量: ");
  r15 = cn_var_electron_mass;
  cn_rt_print_float(r15);
  cn_rt_print_string(" kg\n");
  cn_rt_print_string("质子质量: ");
  r16 = cn_var_proton_mass;
  cn_rt_print_float(r16);
  cn_rt_print_string(" kg\n");
  cn_rt_print_string("引力常数: ");
  r17 = cn_var_gravitational_const;
  cn_rt_print_float(r17);
  cn_rt_print_string("\n");
  double cn_var_light_year;
  cn_var_light_year = 9461000000000000.000000;
  double cn_var_parsec;
  cn_var_parsec = 30860000000000000.000000;
  cn_rt_print_string("一光年: ");
  r18 = cn_var_light_year;
  cn_rt_print_float(r18);
  cn_rt_print_string(" m\n");
  cn_rt_print_string("一秒差距: ");
  r19 = cn_var_parsec;
  cn_rt_print_float(r19);
  cn_rt_print_string(" m\n");
  cn_rt_print_string("\n========== 科学计算 ==========\n");
  double cn_var_mass;
  cn_var_mass = 0.001000;
  double cn_var_c_squared;
  cn_var_c_squared = 89875517900000000.000000;
  double cn_var_energy;
  r20 = cn_var_mass;
  r21 = cn_var_c_squared;
  r22 = r20 * r21;
  cn_var_energy = r22;
  cn_rt_print_string("1克物质的能量: ");
  r23 = cn_var_energy;
  cn_rt_print_float(r23);
  cn_rt_print_string(" 焦耳\n");
  return 0;
  cn_rt_exit();
}

